name: photomaster
description: "AI-powered photo analysis application"
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.0+1
  image_picker: ^1.0.7
  image: ^4.1.7
  sensors_plus: ^5.0.0 # 使用最新版本
  # saver_gallery: ^2.0.1
  async: ^2.11.0 # 添加这一行，或者查看pub.dev上最新的稳定版本
  http: ^1.4.0
  native_device_orientation: ^1.1.4
  flutter_tts: ^3.7.0
  flutter_image_compress: ^2.0.1
  provider: ^6.0.5

  cupertino_icons: ^1.0.8
  flutter_markdown: ^0.6.10
  path_provider: ^2.1.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
